services:
  accounts:
    image: "ripanbaidya/accounts:s4"
    container_name: accounts
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "700M"
    networks:
      - easybank
  loans:
    image: "ripanbaidya/loans:s4"
    container_name: loans
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: "700M"
    networks:
      - easybank
  cards:
    image: "ripanbaidya/cards:s4"
    container_name: cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: "700M"
    networks:
      - easybank
networks:
  easybank:
    driver: bridge